wikinimous/config/routes.rb
Rails.application.routes.draw do

  resources :articles

  root 'articles#index'

end

wikinimous/app/models/article.rb
class Article < ActiveRecord::Base
end

wikinimous/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

wikinimous/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.new(article_params)
    article.save
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article.delete
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:name, :description)
  end
end

wikinimous/app/helpers/application_helper.rb
module ApplicationHelper
end

wikinimous/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <%= f.text_field :title %><br />
  <%= f.text_area :content %><br />
  <%= f.submit %>
<% end %>

wikinimous/app/views/articles/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Wikinimous</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/articles/new">New Article</a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

wikinimous/app/views/articles/edit.html.erb
<%= render "form" %>

wikinimous/app/views/articles/index.html.erb
<div class="index">
  <% @articles.each do |article| %>
    <h2><%= link_to article.title, article_path(article) %></h2>
    <p><%= article.content %></p>
  <% end %>
</div>

wikinimous/app/views/articles/new.html.erb
<%= render "form" %>

wikinimous/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.content %></p>
<%= link_to "edit", edit_article_path(@article) %>
<%= link_to "delete", article_path(@article), method: :delete %>
<%= link_to 'back', articles_path %>
<hr>

wikinimous/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikinimous</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
</head>
<body>

  <%= render "navbar" %>
  <%= yield %>

</body>
</html>